In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.newchic.com/mens-sandals-c-4188/?country=63&conversionType=US&from=nav'
html = urlopen(url)

In [3]:
soup = BeautifulSoup(html)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))

In [4]:
data_name = soup.findAll('p', class_='wom_lst_name ellipsis')
data_name

[<p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1543496.html?rmmds=category" target="_blank" title="Men Genuine Leather Casual Outdoor Sandals">Men Genuine Leather Casual Outdoor Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1541509.html?rmmds=category" target="_blank" title="Men Non Slip Beach Casual Leather Sandals">Men Non Slip Beach Casual Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a class="brand" href="">FREETIE</a>
 <a href="https://www.newchic.com/freetie-mens-sandals-4188/p-1296970.html?rmmds=category" target="_blank" title="FREETIE Summer Men Multiple Adjustable Beach Sandals">FREETIE Summer Men Multiple Adjustable Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1540211.html?rmmds=category" target="_blank" title="Men Cloth Non-slip Casual Beach Sandals ">Men Cloth Non-slip Casual Beach Sandals </a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1539124.html?rmmds=category" target="_blank" title="Men Hand Stitching Soft Sole Leather Sandals">Men Hand Stitching Soft Sole Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a class="brand" href="">HEMU</a>
 <a href="https://www.newchic.com/hemu-mens-sandals-4188/p-1496096.html?rmmds=category" target="_blank" title="HEMU Men Breathable Non-slip Beach Sandals">HEMU Men Breathable Non-slip Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1536222.html?rmmds=category" target="_blank" title="Men Leather Outdoor Anti-collision Sandals">Men Leather Outdoor Anti-collision Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1536220.html?rmmds=category" target="_blank" title="Men Genuine Cow Leather Beach Sandals">Men Genuine Cow Leather Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1536221.html?rmmds=category" target="_blank" title="Men Clip Toe Water Beach Sandals">Men Clip Toe Water Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1535547.html?rmmds=category" target="_blank" title="Men EVA Hook Loop Casual Beach Sandals">Men EVA Hook Loop Casual Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1535318.html?rmmds=category" target="_blank" title="Men Camouflage Canvas Water Sandals">Men Camouflage Canvas Water Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534765.html?rmmds=category" target="_blank" title="Men Three Hook Loop Non Slip Sandals">Men Three Hook Loop Non Slip Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534688.html?rmmds=category" target="_blank" title="Men Non Slip Outdoor Leather Sandals ">Men Non Slip Outdoor Leather Sandals </a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534689.html?rmmds=category" target="_blank" title="Men Non Slip Casual Leather Sandals ">Men Non Slip Casual Leather Sandals </a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534687.html?rmmds=category" target="_blank" title="Men Roma Fabric Casual Beach Sandals">Men Roma Fabric Casual Beach Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534684.html?rmmds=category" target="_blank" title="Men Non Slip Beach Casual Leather Sandals">Men Non Slip Beach Casual Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1534685.html?rmmds=category" target="_blank" title="Men Hand Stitching Non Slip Leather Sandals">Men Hand Stitching Non Slip Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1533325.html?rmmds=category" target="_blank" title="Men Toe Protetive Outdoor Hiking Sandals">Men Toe Protetive Outdoor Hiking Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1533320.html?rmmds=category" target="_blank" title="Men Microfiber Leather Hole Sandals ">Men Microfiber Leather Hole Sandals </a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1531680.html?rmmds=category" target="_blank" title="Men Drainable Sole Outdoor Closed Toe Water Sandals">Men Drainable Sole Outdoor Closed Toe Water Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1529065.html?rmmds=category" target="_blank" title="Men Three Hook Loop Outdoor Hiking Sandals">Men Three Hook Loop Outdoor Hiking Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1529064.html?rmmds=category" target="_blank" title="Men Side Lace Up Comfy Soft Beach Water Sandals">Men Side Lace Up Comfy Soft Beach Water Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1474691.html?rmmds=category" target="_blank" title="Men Hook Loop Slip Resistant Sandals">Men Hook Loop Slip Resistant Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1528629.html?rmmds=category" target="_blank" title="Men Genuine Leather Hiking Waking Water Sandals">Men Genuine Leather Hiking Waking Water Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1526641.html?rmmds=category" target="_blank" title="Men Hole Beach Water Shoes">Men Hole Beach Water Shoes</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1526642.html?rmmds=category" target="_blank" title="Men Comfy Soft Sole Water Beach Casual Sandals">Men Comfy Soft Sole Water Beach Casual Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1523215.html?rmmds=category" target="_blank" title="Men Hollow Out Hole Water Sandals">Men Hollow Out Hole Water Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1523209.html?rmmds=category" target="_blank" title="Men Genuine Leather Outdoor Hiking Sandals">Men Genuine Leather Outdoor Hiking Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1523204.html?rmmds=category" target="_blank" title="Men Oil Leather Toe Protective Water Slippers">Men Oil Leather Toe Protective Water Slippers</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1523206.html?rmmds=category" target="_blank" title="Men Outdoor Leather Splicing Hiking Sandals">Men Outdoor Leather Splicing Hiking Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1522009.html?rmmds=category" target="_blank" title="Men Toe Protetive Outdoor Leather Sandals">Men Toe Protetive Outdoor Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1522006.html?rmmds=category" target="_blank" title="Men Outdoor Anti-collision Toe Hiking Sandals">Men Outdoor Anti-collision Toe Hiking Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1522007.html?rmmds=category" target="_blank" title="Men Outdoor Slip Resistant Soft Leather Sandals">Men Outdoor Slip Resistant Soft Leather Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1520332.html?rmmds=category" target="_blank" title="Men Hand Stitching Leather Soft Sandals">Men Hand Stitching Leather Soft Sandals</a>
 </p>, <p class="wom_lst_name ellipsis">
 <a href="https://www.newchic.com/mens-sandals-4188/p-1495907.html?rmmds=category" target="_blank" title="Men Soft Bottom  Casual Slip Driver Shoes Beach Shoes">Men Soft Bottom  Casual Slip Driver Shoes Beach Shoes</a>
 </p>]

In [5]:
## Clean Data ##
import re
Names = []
for li in data_name:
    str_name = str(li)
    pattern = '<.*?>'
    clean_name = re.sub(pattern, '', str_name)
    Names.append(clean_name)
Names

['\nMen Genuine Leather Casual Outdoor Sandals\n',
 '\nMen Non Slip Beach Casual Leather Sandals\n',
 '\nFREETIE\nFREETIE Summer Men Multiple Adjustable Beach Sandals\n',
 '\nMen Cloth Non-slip Casual Beach Sandals \n',
 '\nMen Hand Stitching Soft Sole Leather Sandals\n',
 '\nHEMU\nHEMU Men Breathable Non-slip Beach Sandals\n',
 '\nMen Leather Outdoor Anti-collision Sandals\n',
 '\nMen Genuine Cow Leather Beach Sandals\n',
 '\nMen Clip Toe Water Beach Sandals\n',
 '\nMen EVA Hook Loop Casual Beach Sandals\n',
 '\nMen Camouflage Canvas Water Sandals\n',
 '\nMen Three Hook Loop Non Slip Sandals\n',
 '\nMen Non Slip Outdoor Leather Sandals \n',
 '\nMen Non Slip Casual Leather Sandals \n',
 '\nMen Roma Fabric Casual Beach Sandals\n',
 '\nMen Non Slip Beach Casual Leather Sandals\n',
 '\nMen Hand Stitching Non Slip Leather Sandals\n',
 '\nMen Toe Protetive Outdoor Hiking Sandals\n',
 '\nMen Microfiber Leather Hole Sandals \n',
 '\nMen Drainable Sole Outdoor Closed Toe Water Sandals\n',
 '\nMen Three Hook Loop Outdoor Hiking Sandals\n',
 '\nMen Side Lace Up Comfy Soft Beach Water Sandals\n',
 '\nMen Hook Loop Slip Resistant Sandals\n',
 '\nMen Genuine Leather Hiking Waking Water Sandals\n',
 '\nMen Hole Beach Water Shoes\n',
 '\nMen Comfy Soft Sole Water Beach Casual Sandals\n',
 '\nMen Hollow Out Hole Water Sandals\n',
 '\nMen Genuine Leather Outdoor Hiking Sandals\n',
 '\nMen Oil Leather Toe Protective Water Slippers\n',
 '\nMen Outdoor Leather Splicing Hiking Sandals\n',
 '\nMen Toe Protetive Outdoor Leather Sandals\n',
 '\nMen Outdoor Anti-collision Toe Hiking Sandals\n',
 '\nMen Outdoor Slip Resistant Soft Leather Sandals\n',
 '\nMen Hand Stitching Leather Soft Sandals\n',
 '\nMen Soft Bottom  Casual Slip Driver Shoes Beach Shoes\n']

In [6]:
x = pd.Index(range(105,140))
print(x)

RangeIndex(start=105, stop=140, step=1)

In [7]:
df = pd.DataFrame(Names,index=x)
df.head()

                                                     0
105     \nMen Genuine Leather Casual Outdoor Sandals\n
106      \nMen Non Slip Beach Casual Leather Sandals\n
107  \nFREETIE\nFREETIE Summer Men Multiple Adjusta...
108       \nMen Cloth Non-slip Casual Beach Sandals \n
109   \nMen Hand Stitching Soft Sole Leather Sandals\n

In [8]:
df[0] = df[0].str.strip('\n')
df.head()

                                                     0
105         Men Genuine Leather Casual Outdoor Sandals
106          Men Non Slip Beach Casual Leather Sandals
107  FREETIE\nFREETIE Summer Men Multiple Adjustabl...
108           Men Cloth Non-slip Casual Beach Sandals
109       Men Hand Stitching Soft Sole Leather Sandals

In [9]:
df.rename(columns={0:'Names'}, inplace=True)

In [10]:
df['Names'].replace('\n','', regex=True, inplace=True)
df

                                                 Names
105         Men Genuine Leather Casual Outdoor Sandals
106          Men Non Slip Beach Casual Leather Sandals
107  FREETIEFREETIE Summer Men Multiple Adjustable ...
108           Men Cloth Non-slip Casual Beach Sandals
109       Men Hand Stitching Soft Sole Leather Sandals
110     HEMUHEMU Men Breathable Non-slip Beach Sandals
111         Men Leather Outdoor Anti-collision Sandals
112              Men Genuine Cow Leather Beach Sandals
113                   Men Clip Toe Water Beach Sandals
114             Men EVA Hook Loop Casual Beach Sandals
115                Men Camouflage Canvas Water Sandals
116               Men Three Hook Loop Non Slip Sandals
117              Men Non Slip Outdoor Leather Sandals
118               Men Non Slip Casual Leather Sandals
119               Men Roma Fabric Casual Beach Sandals
120          Men Non Slip Beach Casual Leather Sandals
121        Men Hand Stitching Non Slip Leather Sandals
122           Men Toe Protetive Outdoor Hiking Sandals
123               Men Microfiber Leather Hole Sandals
124  Men Drainable Sole Outdoor Closed Toe Water Sa...
125         Men Three Hook Loop Outdoor Hiking Sandals
126    Men Side Lace Up Comfy Soft Beach Water Sandals
127               Men Hook Loop Slip Resistant Sandals
128    Men Genuine Leather Hiking Waking Water Sandals
129                         Men Hole Beach Water Shoes
130     Men Comfy Soft Sole Water Beach Casual Sandals
131                  Men Hollow Out Hole Water Sandals
132         Men Genuine Leather Outdoor Hiking Sandals
133      Men Oil Leather Toe Protective Water Slippers
134        Men Outdoor Leather Splicing Hiking Sandals
135          Men Toe Protetive Outdoor Leather Sandals
136      Men Outdoor Anti-collision Toe Hiking Sandals
137    Men Outdoor Slip Resistant Soft Leather Sandals
138            Men Hand Stitching Leather Soft Sandals
139  Men Soft Bottom  Casual Slip Driver Shoes Beac...

In [11]:
data_price = soup.findAll('span', class_='price product-price-js')
data_price

[<span class="price product-price-js" oriprice="43.17" rule_final_price="">725.69E£</span>,
 <span class="price product-price-js" oriprice="19.99" rule_final_price="">336.03E£</span>,
 <span class="price product-price-js" oriprice="24.38" rule_final_price="">409.83E£</span>,
 <span class="price product-price-js" oriprice="24.89" rule_final_price="">418.40E£</span>,
 <span class="price product-price-js" oriprice="47.54" rule_final_price="">799.15E£</span>,
 <span class="price product-price-js" oriprice="18.7" rule_final_price="">314.35E£</span>,
 <span class="price product-price-js" oriprice="47.97" rule_final_price="">806.37E£</span>,
 <span class="price product-price-js" oriprice="52.37" rule_final_price="">880.34E£</span>,
 <span class="price product-price-js" oriprice="35.79" rule_final_price="">601.63E£</span>,
 <span class="price product-price-js" oriprice="23.05" rule_final_price="">387.47E£</span>,
 <span class="price product-price-js" oriprice="24.79" rule_final_price="">416.72E£</span>,
 <span class="price product-price-js" oriprice="47.85" rule_final_price="">804.36E£</span>,
 <span class="price product-price-js" oriprice="48.73" rule_final_price="">819.15E£</span>,
 <span class="price product-price-js" oriprice="37.21" rule_final_price="">625.50E£</span>,
 <span class="price product-price-js" oriprice="18.58" rule_final_price="">312.33E£</span>,
 <span class="price product-price-js" oriprice="41.58" rule_final_price="">698.96E£</span>,
 <span class="price product-price-js" oriprice="34.23" rule_final_price="">575.41E£</span>,
 <span class="price product-price-js" oriprice="47.95" rule_final_price="">806.04E£</span>,
 <span class="price product-price-js" oriprice="46.97" rule_final_price="">789.56E£</span>,
 <span class="price product-price-js" oriprice="38.45" rule_final_price="">646.34E£</span>,
 <span class="price product-price-js" oriprice="51.75" rule_final_price="">869.92E£</span>,
 <span class="price product-price-js" oriprice="33.85" rule_final_price="">569.02E£</span>,
 <span class="price product-price-js" oriprice="54.87" rule_final_price="">922.36E£</span>,
 <span class="price product-price-js" oriprice="55.45" rule_final_price="">932.11E£</span>,
 <span class="price product-price-js" oriprice="16.78" rule_final_price="">282.07E£</span>,
 <span class="price product-price-js" oriprice="27.65" rule_final_price="">464.80E£</span>,
 <span class="price product-price-js" oriprice="18.35" rule_final_price="">308.46E£</span>,
 <span class="price product-price-js" oriprice="52.41" rule_final_price="">881.01E£</span>,
 <span class="price product-price-js" oriprice="45.73" rule_final_price="">768.72E£</span>,
 <span class="price product-price-js" oriprice="49.73" rule_final_price="">835.96E£</span>,
 <span class="price product-price-js" oriprice="52.71" rule_final_price="">886.05E£</span>,
 <span class="price product-price-js" oriprice="48.74" rule_final_price="">819.32E£</span>,
 <span class="price product-price-js" oriprice="48.54" rule_final_price="">815.96E£</span>,
 <span class="price product-price-js" oriprice="51.75" rule_final_price="">869.92E£</span>,
 <span class="price product-price-js" oriprice="13.29" rule_final_price="">223.40E£</span>]

In [12]:
## Clean Data ##
import re
Prices = []
for li in data_price:
    str_name = str(li)
    pattern = '<.*?>'
    clean_name = re.sub(pattern, '', str_name)
    Prices.append(clean_name)
Prices

['725.69E£',
 '336.03E£',
 '409.83E£',
 '418.40E£',
 '799.15E£',
 '314.35E£',
 '806.37E£',
 '880.34E£',
 '601.63E£',
 '387.47E£',
 '416.72E£',
 '804.36E£',
 '819.15E£',
 '625.50E£',
 '312.33E£',
 '698.96E£',
 '575.41E£',
 '806.04E£',
 '789.56E£',
 '646.34E£',
 '869.92E£',
 '569.02E£',
 '922.36E£',
 '932.11E£',
 '282.07E£',
 '464.80E£',
 '308.46E£',
 '881.01E£',
 '768.72E£',
 '835.96E£',
 '886.05E£',
 '819.32E£',
 '815.96E£',
 '869.92E£',
 '223.40E£']

In [13]:
df1 = pd.DataFrame(Prices, index=x)
df1

            0
105  725.69E£
106  336.03E£
107  409.83E£
108  418.40E£
109  799.15E£
110  314.35E£
111  806.37E£
112  880.34E£
113  601.63E£
114  387.47E£
115  416.72E£
116  804.36E£
117  819.15E£
118  625.50E£
119  312.33E£
120  698.96E£
121  575.41E£
122  806.04E£
123  789.56E£
124  646.34E£
125  869.92E£
126  569.02E£
127  922.36E£
128  932.11E£
129  282.07E£
130  464.80E£
131  308.46E£
132  881.01E£
133  768.72E£
134  835.96E£
135  886.05E£
136  819.32E£
137  815.96E£
138  869.92E£
139  223.40E£

In [14]:
df1.rename(columns={0:'Prices'}, inplace=True)
df1.head()

       Prices
105  725.69E£
106  336.03E£
107  409.83E£
108  418.40E£
109  799.15E£

In [15]:
df1['Prices'].replace('E£','', regex=True, inplace=True)
df1

     Prices
105  725.69
106  336.03
107  409.83
108  418.40
109  799.15
110  314.35
111  806.37
112  880.34
113  601.63
114  387.47
115  416.72
116  804.36
117  819.15
118  625.50
119  312.33
120  698.96
121  575.41
122  806.04
123  789.56
124  646.34
125  869.92
126  569.02
127  922.36
128  932.11
129  282.07
130  464.80
131  308.46
132  881.01
133  768.72
134  835.96
135  886.05
136  819.32
137  815.96
138  869.92
139  223.40

In [16]:
df1['Prices'].replace(',','',regex=True, inplace=True)
df1.tail()

     Prices
135  886.05
136  819.32
137  815.96
138  869.92
139  223.40

In [17]:
df1['Prices'] = pd.to_numeric(df1['Prices'])
df1.tail()

     Prices
135  886.05
136  819.32
137  815.96
138  869.92
139  223.40

In [18]:
df_sandals = df.join(df1)
df_sandals

                                                 Names  Prices
105         Men Genuine Leather Casual Outdoor Sandals  725.69
106          Men Non Slip Beach Casual Leather Sandals  336.03
107  FREETIEFREETIE Summer Men Multiple Adjustable ...  409.83
108           Men Cloth Non-slip Casual Beach Sandals   418.40
109       Men Hand Stitching Soft Sole Leather Sandals  799.15
110     HEMUHEMU Men Breathable Non-slip Beach Sandals  314.35
111         Men Leather Outdoor Anti-collision Sandals  806.37
112              Men Genuine Cow Leather Beach Sandals  880.34
113                   Men Clip Toe Water Beach Sandals  601.63
114             Men EVA Hook Loop Casual Beach Sandals  387.47
115                Men Camouflage Canvas Water Sandals  416.72
116               Men Three Hook Loop Non Slip Sandals  804.36
117              Men Non Slip Outdoor Leather Sandals   819.15
118               Men Non Slip Casual Leather Sandals   625.50
119               Men Roma Fabric Casual Beach Sandals  312.33
120          Men Non Slip Beach Casual Leather Sandals  698.96
121        Men Hand Stitching Non Slip Leather Sandals  575.41
122           Men Toe Protetive Outdoor Hiking Sandals  806.04
123               Men Microfiber Leather Hole Sandals   789.56
124  Men Drainable Sole Outdoor Closed Toe Water Sa...  646.34
125         Men Three Hook Loop Outdoor Hiking Sandals  869.92
126    Men Side Lace Up Comfy Soft Beach Water Sandals  569.02
127               Men Hook Loop Slip Resistant Sandals  922.36
128    Men Genuine Leather Hiking Waking Water Sandals  932.11
129                         Men Hole Beach Water Shoes  282.07
130     Men Comfy Soft Sole Water Beach Casual Sandals  464.80
131                  Men Hollow Out Hole Water Sandals  308.46
132         Men Genuine Leather Outdoor Hiking Sandals  881.01
133      Men Oil Leather Toe Protective Water Slippers  768.72
134        Men Outdoor Leather Splicing Hiking Sandals  835.96
135          Men Toe Protetive Outdoor Leather Sandals  886.05
136      Men Outdoor Anti-collision Toe Hiking Sandals  819.32
137    Men Outdoor Slip Resistant Soft Leather Sandals  815.96
138            Men Hand Stitching Leather Soft Sandals  869.92
139  Men Soft Bottom  Casual Slip Driver Shoes Beac...  223.40

In [20]:
df_sandals.shape

(35, 2)

In [26]:
df_f = pd.DataFrame({'Type':['Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals','Sandals']},index=x)
df_f

        Type
105  Sandals
106  Sandals
107  Sandals
108  Sandals
109  Sandals
110  Sandals
111  Sandals
112  Sandals
113  Sandals
114  Sandals
115  Sandals
116  Sandals
117  Sandals
118  Sandals
119  Sandals
120  Sandals
121  Sandals
122  Sandals
123  Sandals
124  Sandals
125  Sandals
126  Sandals
127  Sandals
128  Sandals
129  Sandals
130  Sandals
131  Sandals
132  Sandals
133  Sandals
134  Sandals
135  Sandals
136  Sandals
137  Sandals
138  Sandals
139  Sandals

In [27]:
df_data = df_f.join(df_sandals)
df_data

        Type                                              Names  Prices
105  Sandals         Men Genuine Leather Casual Outdoor Sandals  725.69
106  Sandals          Men Non Slip Beach Casual Leather Sandals  336.03
107  Sandals  FREETIEFREETIE Summer Men Multiple Adjustable ...  409.83
108  Sandals           Men Cloth Non-slip Casual Beach Sandals   418.40
109  Sandals       Men Hand Stitching Soft Sole Leather Sandals  799.15
110  Sandals     HEMUHEMU Men Breathable Non-slip Beach Sandals  314.35
111  Sandals         Men Leather Outdoor Anti-collision Sandals  806.37
112  Sandals              Men Genuine Cow Leather Beach Sandals  880.34
113  Sandals                   Men Clip Toe Water Beach Sandals  601.63
114  Sandals             Men EVA Hook Loop Casual Beach Sandals  387.47
115  Sandals                Men Camouflage Canvas Water Sandals  416.72
116  Sandals               Men Three Hook Loop Non Slip Sandals  804.36
117  Sandals              Men Non Slip Outdoor Leather Sandals   819.15
118  Sandals               Men Non Slip Casual Leather Sandals   625.50
119  Sandals               Men Roma Fabric Casual Beach Sandals  312.33
120  Sandals          Men Non Slip Beach Casual Leather Sandals  698.96
121  Sandals        Men Hand Stitching Non Slip Leather Sandals  575.41
122  Sandals           Men Toe Protetive Outdoor Hiking Sandals  806.04
123  Sandals               Men Microfiber Leather Hole Sandals   789.56
124  Sandals  Men Drainable Sole Outdoor Closed Toe Water Sa...  646.34
125  Sandals         Men Three Hook Loop Outdoor Hiking Sandals  869.92
126  Sandals    Men Side Lace Up Comfy Soft Beach Water Sandals  569.02
127  Sandals               Men Hook Loop Slip Resistant Sandals  922.36
128  Sandals    Men Genuine Leather Hiking Waking Water Sandals  932.11
129  Sandals                         Men Hole Beach Water Shoes  282.07
130  Sandals     Men Comfy Soft Sole Water Beach Casual Sandals  464.80
131  Sandals                  Men Hollow Out Hole Water Sandals  308.46
132  Sandals         Men Genuine Leather Outdoor Hiking Sandals  881.01
133  Sandals      Men Oil Leather Toe Protective Water Slippers  768.72
134  Sandals        Men Outdoor Leather Splicing Hiking Sandals  835.96
135  Sandals          Men Toe Protetive Outdoor Leather Sandals  886.05
136  Sandals      Men Outdoor Anti-collision Toe Hiking Sandals  819.32
137  Sandals    Men Outdoor Slip Resistant Soft Leather Sandals  815.96
138  Sandals            Men Hand Stitching Leather Soft Sandals  869.92
139  Sandals  Men Soft Bottom  Casual Slip Driver Shoes Beac...  223.40

In [28]:
df_data.index.name='ID'

In [29]:
df_data.to_csv('Sandals.csv')